version: '3.9'

services:
  api:
    container_name: api_k_imoveis
    build: .
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: 
      bash -c "yarn typeorm migration:run -d src/data-source && yarn dev" 
    volumes:
      - .:/app
  database:
    container_name: k_imoveis_db
    image: postgres:14
    ports:
      - $PG_PORT:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 4s
      retries: 2
      start_period: 5s